name: Terraform Version Monitoring

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Run Terraform and Report Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "latest"
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init

      - name: Fetch Terraform Version
        id: get-tf-version
        run: |
          TF_VERSION=$(terraform version -json | jq -r '.terraform_version')
          TF_VERSION_NUM=$(echo "$TF_VERSION" | awk -F. '{ printf "%d%02d%02d\n", $1, $2, $3 }')
          echo "Terraform version detected: $TF_VERSION (numeric: $TF_VERSION_NUM)"
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_ENV
          echo "TF_VERSION_NUM=$TF_VERSION_NUM" >> $GITHUB_ENV
      - name: Fetch azurerm Provider Version
        id: get-azurerm-version
        run: |
             AZURERM_VERSION=$(grep 'provider "registry.terraform.io/hashicorp/azurerm"' -A 5 .terraform.lock.hcl | grep version | awk '{print $3}' | tr -d '"')
             AZURERM_VERSION_NUMERIC=$(echo "$AZURERM_VERSION" | awk -F. '{patch=($3=="")?0:$3; printf("%d\n", $1*10000 + $2*100 + patch)}')
             echo "azurerm version: $AZURERM_VERSION -> Numeric: $AZURERM_VERSION_NUMERIC"
             echo "AZURERM_VERSION=$AZURERM_VERSION" >> $GITHUB_ENV
             echo "AZURERM_VERSION_NUMERIC=$AZURERM_VERSION_NUMERIC" >> $GITHUB_ENV
      # - name: Fetch azurerm Provider Version
      #   id: get-azurerm-version
      #   run: |
      #      AZURERM_VERSION=$(grep 'provider "registry.terraform.io/hashicorp/azurerm"' -A 5 .terraform.lock.hcl | grep version | awk '{print $3}' | tr -d '"')
      #      AZURERM_VERSION_NUMERIC=$(echo "$AZURERM_VERSION" | awk -F. '{p=($3=="")?0:$3; printf("%d\n", $1*1000 + $2*10 + p)}')
      #      echo "azurerm version: $AZURERM_VERSION -> Numeric: $AZURERM_VERSION_NUMERIC"
      #      echo "AZURERM_VERSION=$AZURERM_VERSION" >> $GITHUB_ENV
      #      echo "AZURERM_VERSION_NUMERIC=$AZURERM_VERSION_NUMERIC" >> $GITHUB_ENV

      - name: Send Terraform Version to Datadog
        run: |
          echo "Sending Terraform version: $TF_VERSION_NUM to Datadog"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            -d '{
                  "series": [{
                    "metric": "terra.version",
                    "points": [['"$(date +%s)"', '"$TF_VERSION_NUM"']],
                    "type": "gauge",
                    "tags": ["env:github", "status:version"]
                  }]
                }' \
            "https://api.us5.datadoghq.com/api/v1/series"

      - name: Send Azurerm Version to Datadog
        run: |
          AZURERM_VERSION_NUMERIC="${{ env.AZURERM_VERSION_NUMERIC }}"
          echo "Sending AZURERM_VERSION_NUMERIC: $AZURERM_VERSION_NUMERIC"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            -d '{
                  "series": [{
                    "metric": "rm_version",
                    "points": [['"$(date +%s)"', '"$AZURERM_VERSION_NUMERIC"']],
                    "type": "gauge",
                    "tags": ["source:github", "status:version"]
                  }]
                }' \
            "https://api.us5.datadoghq.com/api/v1/series"
