name: Monitor GitHub Token Expiry

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-token-expiry:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check GitHub Token Expiry for Token 1
        run: |
          GITHUB_TOKEN_1=${{ secrets.GITHUB_TOKEN_1 }}
          EXPIRATION_DATE_1="2026-02-03T00:00:00Z"
          EXPIRATION_TIMESTAMP_1=$(date -d "$EXPIRATION_DATE_1" +%s)
          CURRENT_TIMESTAMP=$(date +%s)
          DAYS_UNTIL_EXPIRY_1=$((($EXPIRATION_TIMESTAMP_1 - $CURRENT_TIMESTAMP) / 86400))
          echo "Github USER_READONLY_TOKEN 1 is going to expire in $DAYS_UNTIL_EXPIRY_1 days."

          curl -X POST \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            -d '{
                  "series": [{
                  "metric": "github.token.expiry.days_left",
                  "points": [['"$(date +%s)"', '"$DAYS_UNTIL_EXPIRY_1"']],
                  "type": "gauge",
                  "tags": ["source:github", "token:token_1", "status:expiry_warning"]
                          }]
              }' \
           "https://api.us3.datadoghq.com/api/v1/series"

      - name: Check GitHub Token Expiry for Token 2
        run: |
          GITHUB_TOKEN_2=${{ secrets.GITHUB_TOKEN_2 }}
          EXPIRATION_DATE_2="2026-03-01T00:00:00Z"
          EXPIRATION_TIMESTAMP_2=$(date -d "$EXPIRATION_DATE_2" +%s)
          DAYS_UNTIL_EXPIRY_2=$((($EXPIRATION_TIMESTAMP_2 - $CURRENT_TIMESTAMP) / 86400))
          echo "Github USER_READONLY_TOKEN 2 is going to expire in $DAYS_UNTIL_EXPIRY_2 days."

          curl -X POST \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            -d '{
                  "series": [{
                  "metric": "github.token.expiry.days_left",
                  "points": [['"$(date +%s)"', '"$DAYS_UNTIL_EXPIRY_2"']],
                  "type": "gauge",
                  "tags": ["source:github", "token:token_2", "status:expiry_warning"]
                          }]
              }' \
           "https://api.us3.datadoghq.com/api/v1/series"

            #       "title": "GitHub Token Expiry Warning",
            #       "text": "Token expires in '"$DAYS_UNTIL_EXPIRY"' days kunmun    here .",
                  # "tags": ["token:github", "status:expiry_warning", "expiry:'"$DAYS_UNTIL_EXPIRY"' days"],
            #       "priority": "normal"
            #     }' \
            # "https://api.datadoghq.com/api/v1/events"

      
