name: Monitor GitHub Token Expiry

on:
  schedule:
  - cron: '40 8 * * *'  # 8:40 AM UTC (equivalent to 2:10 PM IST)

  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub UI

jobs:
  check-token-expiry:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check GitHub Token Expiry
        run: |
          # Use the GitHub token stored in GitHub Secrets
          GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}  # Reference your stored GitHub Token
          
          # GitHub token expiration date (stored as a GitHub secret)
          EXPIRATION_DATE=${{ secrets.PGITHUB_TOKEN_EXPIRY_DATE }}  # Corrected secret name here
          
          # Convert the expiration date to Unix timestamp (in seconds)
          EXPIRATION_TIMESTAMP=$(date -d "$EXPIRATION_DATE" +%s)
          CURRENT_TIMESTAMP=$(date +%s)
          
          # Calculate how many days until token expiry
          DAYS_UNTIL_EXPIRY=$((($EXPIRATION_TIMESTAMP - $CURRENT_TIMESTAMP) / 86400))
          
          echo "Token expires in $DAYS_UNTIL_EXPIRY days."
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            -d '{
                  "title": "GitHub Token Expiry Warning",
                  "text": "Token expires in '"$DAYS_UNTIL_EXPIRY"' days kunmun    here .",
                  "tags": ["token:github", "status:expiry_warning"],
                  "priority": "normal"
                }' \
            "https://api.datadoghq.com/api/v1/events"

          # # Step 2: Check if the token is expiring within the next 7 days
          # if [ "$DAYS_UNTIL_EXPIRY" -le 7 ]; then
          #   echo "Token is expiring soon! Sending alert to Datadog."
            
          #   # Send a custom Datadog event about the token expiry
          #   curl -X POST \
          #     -H "Content-Type: application/json" \
          #     -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
          #     -d '{
          #           "title": "GitHub Token Expiry Warning",
          #           "text": "The GitHub token will expire in '"$DAYS_UNTIL_EXPIRY"' days. Please renew it soon.",
          #           "tags": ["token:github", "status:expiry_warning"],
          #           "priority": "normal"
          #         }' \
          #     "https://api.datadoghq.com/api/v1/events"
          # else
          #   echo "Token is valid for $DAYS_UNTIL_EXPIRY days. No action needed."
          # fi
