name: Monitor GitHub Token Expiry

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch: 

jobs:
  check-token-expiry:
    runs-on: ubuntu-latest

    steps:
      - name: Check GitHub Token Expiry
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          EXPIRATION_DATE1="2025-02-19T00:00:00Z"  
          EXPIRATION_TIMESTAMP1=$(date -d "$EXPIRATION_DATE1" +%s)
          CURRENT_TIMESTAMP1=$(date +%s)
          DAYS_UNTIL_EXPIRY1=$((($EXPIRATION_TIMESTAMP1 - $CURRENT_TIMESTAMP1) / 86400))
          echo "Github PUJA_1 is going to expire in $DAYS_UNTIL_EXPIRY1 days."
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            -d '{
                  "series": [{
                  "metric": "github.1st.token.expiry.days_left",
                  "points": [['"$(date +%s)"', '"$DAYS_UNTIL_EXPIRY1"']],
                  "type": "gauge",
                  "tags": ["source:github", "tok:puja_1", "status:expiry_warning"]
                          }]
              }' \
           "https://api.us5.datadoghq.com/api/v1/series"
      - name: Check GitHub Token Expiry
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          EXPIRATION_DATE2="2025-04-15T00:00:00Z"  
          EXPIRATION_TIMESTAMP2=$(date -d "$EXPIRATION_DATE2" +%s)
          CURRENT_TIMESTAMP2=$(date +%s)
          DAYS_UNTIL_EXPIRY2=$((($EXPIRATION_TIMESTAMP2 - $CURRENT_TIMESTAMP2) / 86400))
          echo "Github PUJA_2 is going to expire in $DAYS_UNTIL_EXPIRY2 days."
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            -d '{
                  "series": [{
                  "metric": "github.2nd.token.expiry.days_left",
                  "points": [['"$(date +%s)"', '"$DAYS_UNTIL_EXPIRY2"']],
                  "type": "gauge",
                  "tags": ["source:github", "tok:puja_2", "status:expiry_warning"]
                          }]
              }' \
           "https://api.us5.datadoghq.com/api/v1/series"


            #       "title": "GitHub Token Expiry Warning",
            #       "text": "Token expires in '"$DAYS_UNTIL_EXPIRY"' days kunmun    here .",
                  # "tags": ["token:github", "status:expiry_warning", "expiry:'"$DAYS_UNTIL_EXPIRY"' days"],
            #       "priority": "normal"
            #     }' \
            # "https://api.datadoghq.com/api/v1/events"

      
