name: Monitor Terraform and Azurerm Versions from TF Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  monitor-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Terraform Version from .tf file
        id: tf_version
        run: |
          # Extract Terraform version from required_version in main.tf
          TF_VERSION=$(grep -oP 'required_version\s*=\s*"\K[^\"]+' main.tf)
          if [ -z "$TF_VERSION" ]; then
            echo "Terraform version not found in main.tf"
            exit 1
          fi
          echo "Terraform version found: $TF_VERSION"
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_ENV

      - name: Read Azurerm Provider Version from .tf file
        id: azurerm_version
        run: |
          # Extract Azurerm provider version from main.tf
          AZURERM_VERSION=$(grep -oP 'azurerm\s*=\s*{\s*version\s*=\s*"\K[^\"]+' main.tf)
          if [ -z "$AZURERM_VERSION" ]; then
            echo "Azurerm provider version not found in main.tf"
            exit 1
          fi
          echo "Azurerm provider version found: $AZURERM_VERSION"
          echo "AZURERM_VERSION=$AZURERM_VERSION" >> $GITHUB_ENV

      - name: Send Terraform Version and Azurerm Version to Datadog
        run: |
          VERSION="${{ env.TF_VERSION }}"
          AZURERM_VERSION="${{ env.AZURERM_VERSION }}"
          TIMESTAMP=$(date +%s)
          
          # Convert version (e.g., 1.6.2 → 10602)
          VERSION_NUMERIC=$(echo $VERSION | awk -F. '{ printf("%d%02d%02d", $1,$2,$3) }')
          AZURERM_VERSION_NUMERIC=$(echo $AZURERM_VERSION | awk -F. '{ printf("%d%02d%02d", $1,$2,$3) }')

          # Send the version data to Datadog
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            -d '{
                  "series": [{
                    "metric": "terraform.cli.version",
                    "points": [['"$(date +%s)"', '"$VERSION_NUMERIC"']],
                    "type": "gauge",
                    "tags": ["source:github", "repo:${{ github.repository }}", "version:$VERSION"]
                  },
                  {
                    "metric": "azurerm.provider.version",
                    "points": [['"$(date +%s)"', '"$AZURERM_VERSION_NUMERIC"']],
                    "type": "gauge",
                    "tags": ["source:github", "repo:${{ github.repository }}", "version:$AZURERM_VERSION"]
                  }]
              }' \
           "https://api.datadoghq.com/api/v1/series"
